# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf01fcfc3250f24c984f470d4c7c40e139e6b934544113eacf9161a0f9dab3161430416bfbcc6e57c0fc2dc01427cb5726b1b841490ac875c0ad6acb6abe5b32

test:
  secret_key_base: 319bb17ee3ba06552f73638e4a44ad7e2477b9c383b5d7ccd66b087ae6176a75dd71f8801ffe1e99c820278421ad1c389af76bbece78d062f2535c1bf3dbe13b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
